repos:
  - repo: local
    hooks:
      - id: ruff-check-fix
        name: ruff check --fix
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.30  # use latest available tag
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--output-file=requirements.txt", "--no-hashes"]